project:
  type: website

website:
  title: "Movements of Minumums, Maximums and Moments"
  sidebar:
    style: "docked"
    contents:
      - href: index.qmd
        text: Full Sonification
      - href: data.qmd
        text: Data and Processing
      # - section: "Sonification Design"
      #   contents:
      #     - href: snippets/averages.qmd
      #       text: Averages 
      #     - href: snippets/min_max.qmd
      #       text: Mins and Maxes
      #     - href: snippets/everything.qmd
      #       text: Everything and Exceedances
      - href: video.qmd
      - href: about.qmd
        text: "About Us"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

