---
title: "About Us"
---

On the statistics side, sonification arose from prior joint work among Dr. Julia Schedler, Donya Behroozi, and Dr. Sinem Demirci.

| Name | Role | Abount |
|----|----|----|
| [Dr. Julia Schedler](https://statistics.calpoly.edu/julia-schedler) | Conceptualization, data processing and sourcing, sonification design and implementation, animation. | Dr. Julia Schedler is Assistant Professor in the Statistics Department in the Bailey College of Science and Mathematics at Cal Poly SLO. Besides sonification, Dr. Schedler works on time series modeling, spatial modeling, and workflows for customizing learning experiences. |
| Donya Behroozi | Conceptualization and sonification function code | Recent undergraduate and soon-to-be masters student at Cal Poly. |
| [Dr. Sinem Demirci](https://statistics.calpoly.edu/sinem-demirci) | Conceptualization and project management | Lecturer in the Statistics Department in the Bailey College of Science and Mathematics at Cal Poly SLO. Dr. Demirci's research interests include Statistics and Data Science education and environmental and sustainability education. |

On the performance side, Josh Schneider choreographed the dance and designed the lighting sequence.

### California Coastal Classroom Research Collaborative

We are incredibly grateful to the feedback from our C3RC collaborations, Dr. Jeanine Scaramozzino, Dr. Aaron Liggett, and Annica Wu (the artist behind the poppy art on the event fliers and the video!).

Further information is available on the [3CRC Webpage](https://guides.lib.calpoly.edu/steam) (under construction).

### Additional Acknowledgements

Additional gratitude to everyone on the math department side of the 2nd floor of faculty offices east, especially Dr. Charlotte Mann and Dr. Ulric Lund, for listening to and/or being annoyed by drafts of the sonifications.

And finally, I am extremely grateful to the funding organization within Cal Poly, unfortunately I did not get my ducks in a row so I will need to update with that information later. 🦆
